# Generated by Django 5.1.2 on 2025-04-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_campañas', models.FloatField()),
                ('campanas_activa', models.IntegerField()),
                ('Cantidad_modelos', models.IntegerField()),
            ],
        ),
    ]
