# Generated by Django 5.1.2 on 2025-04-12 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header_Modelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('cedula', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Header_Modelos',
            },
        ),
        migrations.CreateModel(
            name='SaldoAcumulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_contratos', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo_de_movimiento', models.CharField()),
                ('monto', models.FloatField(default=0.0)),
                ('saldo_disponible', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'WalletModelos',
            },
        ),
        migrations.CreateModel(
            name='TipoDeCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'TipoDeCuenta',
            },
        ),
        migrations.CreateModel(
            name='tallas_modelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camisa', models.CharField(blank=True, max_length=100, null=True)),
                ('pantalon', models.CharField(blank=True, max_length=100, null=True)),
                ('zapatos', models.CharField(blank=True, max_length=100, null=True)),
                ('vestimenta', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_perfiles.header_modelos')),
            ],
            options={
                'db_table': 'tallas_modelos',
            },
        ),
        migrations.AddField(
            model_name='header_modelos',
            name='tipo_de_cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_perfiles.tipodecuenta'),
        ),
    ]
