# Generated by Django 5.1.2 on 2025-04-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodecuenta',
            name='codigo',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
