# Generated by Django 5.1.2 on 2025-04-20 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_perfiles', '0002_tipodecuenta_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saldoacumulado',
            name='cantidad_contratos',
        ),
        migrations.RemoveField(
            model_name='saldoacumulado',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='saldoacumulado',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='saldoacumulado',
            name='tipo_de_movimiento',
        ),
        migrations.AddField(
            model_name='saldoacumulado',
            name='codigo_wallet',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='saldoacumulado',
            name='model_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Wallets', to='app_perfiles.header_modelos'),
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo_de_movimiento', models.CharField(max_length=20)),
                ('monto', models.FloatField(default=0.0)),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transacciones', to='app_perfiles.saldoacumulado')),
            ],
            options={
                'db_table': 'TransccionesWalletsModelos',
            },
        ),
    ]
