# Generated by Django 5.1.7 on 2025-05-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_perfiles', '0003_remove_saldoacumulado_cantidad_contratos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='header_modelos',
            name='edad',
            field=models.IntegerField(null=True),
        ),
    ]
