# Generated by Django 5.1.7 on 2025-05-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_perfiles', '0004_header_modelos_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='header_modelos',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
