# Generated by Django 5.1.7 on 2025-05-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_perfiles', '0006_header_modelos_codigo_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='header_modelos',
            name='numero_tlf',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
