# Generated by Django 5.1.2 on 2025-04-12 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_perfiles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pautas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre_pauta', models.CharField(max_length=50)),
                ('ubicacion_pauta', models.CharField(max_length=50)),
                ('autorizacio_comercial', models.CharField(max_length=50)),
                ('autorizacion_directiva', models.CharField(max_length=50)),
                ('monto_de_pauta', models.FloatField(default=0.0)),
                ('status_pauta', models.CharField(default='PENDIENTE')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_perfiles.header_modelos')),
            ],
            options={
                'db_table': 'Pautas',
            },
        ),
    ]
