# Generated by Django 5.1.7 on 2025-05-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pautasMaker', '0002_alter_pautas_autorizacio_comercial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pautas',
            name='autorizacio_comercial',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
