# Generated by Django 5.1.2 on 2025-04-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('tipo_de_movimiento', models.CharField()),
                ('monto', models.FloatField(blank=True, default=0.0, null=True)),
                ('ultimo_monto', models.FloatField(default=0.0)),
                ('restante_fondo', models.FloatField(default=0.0, null=True)),
            ],
            options={
                'db_table': 'Wallet',
            },
        ),
    ]
